import pandas as pd

# Read the CSV file
df = pd.read_csv("orders.csv")

# Convert 'order_date' column to datetime type
df["order_date"] = pd.to_datetime(df["order_date"])

# Task 1: Compute the total revenue generated by the online store for each month
df["month"] = df["order_date"].dt.to_period("M")
monthly_revenue = df.groupby("month")["product_price"].sum()

# Task 2: Compute the total revenue generated by each product
product_revenue = df.groupby("product_name")["product_price"].sum()

# Task 3: Compute the total revenue generated by each customer
customer_revenue = df.groupby("customer_id")["product_price"].sum()

# Task 4: Identify the top 10 customers by revenue generated
top_customers = customer_revenue.nlargest(10)

# Display the results
print("Task 1: Total revenue generated by the online store for each month")
print(monthly_revenue)
print("\nTask 2: Total revenue generated by each product")
print(product_revenue)
print("\nTask 3: Total revenue generated by each customer")
print(customer_revenue)
print("\nTask 4: Top 10 customers by revenue generated")
print(top_customers)
